### ISSUE TITLE
React 18: Tooltips still not hiding

### ISSUE THREAD

**Issue by ansgarsteinkamp** [ReactTooltip/react-tooltip#769]
With npm's latest version of react-tooltip (version 4.2.21) tooltips still don't hide.

**Comment by svmszcck** [comment]
As a quick fix you can do this until the package is updated:

const [tooltip, showTooltip] = useState(true);

```
<>
 {tooltip && <ReactTooltip effect="solid" />}
 <FaQuestionCircle
              data-tip="hello world"
              onMouseEnter={() => showTooltip(true)}
              onMouseLeave={() => {
                showTooltip(false);
                setTimeout(() => showTooltip(true), 0);
              }}
  />
</>
```

**Comment by ansgarsteinkamp** [comment]
Thank you very much for the quick fix!
Hoping for a package-update, though, since there are hundreds of tooltips in my project.

**Comment by aronhelser** [comment]
Is there a PR that fixes this issue? Can this quick fix be turned into a PR?

**Comment by ansgarsteinkamp** [comment]
Correct me if I'm wrong, but commit [064249c](https://github.com/wwayne/react-tooltip/commit/064249c2d344f5fa639d97994311e484a73156b4) solved the React 18 problem, didn't it?
It's just not part of the npm-package 4.2.21.
The quick fix of svmszcck is really just a quick fix. Not very quick in my case, though.

**Comment by Roundaround** [comment]
The last tag (and therefore npm release) was almost a year ago... @aronhelser do you have the permissions to push tags and make a new npm release?

**Comment by PanRagon** [comment]
Seconded on an NPM-update, there's been a lot of bug-fixes over the past year that should be deployed for them to have any value.

**Comment by aronhelser** [comment]
npm was supposed to be automated, and I no longer remember how to do it. If I get a chance I'll look into it...

**Comment by Kaishley** [comment]
Any luck with the NPM update?

**Comment by sharma-dev** [comment]
This seems to be an issue with the new Strict mode of React. I was having the same issue even in production but it worked fine after I removed Strict Mode from my app.

**Comment by ansgarsteinkamp** [comment]
@aronhelser Another month has passed, no update on NPM. Is there really nobody who can update the NPM-package based on the fixed issues of the past 12 months? The project is stone-dead, isn't it?

**Comment by aronhelser** [comment]
Neither of the maintainers are currently working with React. I've been working exclusively in C++ for the past year. I would be happy to give maintainer access to someone willing to work on the project.

**Comment by alexgurr** [comment]
@aronhelser I'd be happy to try and help as an active maintainer (with the spare time I can find for it). Been using this library for quite some time.

**Comment by aronhelser** [comment]
@wwayne if we'd like to add @alexgurr as a maintainer, I think you would need to do it. WDYT?

**Comment by Kaishley** [comment]
@wwayne kind reminder

**Comment by d4mr** [comment]
@wwayne gentle nudge

**Comment by pdeszynski** [comment]
> npm was supposed to be automated, and I no longer remember how to do it. If I get a chance I'll look into it...

@aronhelser `yarn run semantic-release --publish` ?

**Comment by present-g** [comment]
Hello everybody! What is known with the update?

**Comment by xbjfk** [comment]
If you want to keep strict mode, you can install the latest commit with:
`npm i 'https://github.com/wwayne/react-tooltip/archive/064249c2d344f5fa639d97994311e484a73156b4.tar.gz'`

**Comment by poeck** [comment]
@roggervalf is this something you could do?

**Comment by sundarrajendran** [comment]
Do we have any solution for that? I am experiencing the same issue in production.

**Comment by pdeszynski** [comment]
@sundarrajendran temporarily, until issue is resolved here, you can replace it with a fork of mine https://www.npmjs.com/package/react-tooltip-rc

**Comment by aronhelser** [comment]
@pdeszynski I would like to point to your package as a maintained version of this package in the readme - is this OK with you? Are you able to help with maintaining the project? I am probably going to mark this project as archived/inactive.

**Comment by aronhelser** [comment]
@alexgurr I know you were interested in possibly being maintainer. Maybe you can coordinate with @pdeszynski ?

**Comment by pdeszynski** [comment]
> @pdeszynski I would like to point to your package as a maintained version of this package in the readme - is this OK with you? Are you able to help with maintaining the project? I am probably going to mark this project as archived/inactive.

@aronhelser I don't mind, though if you would like to point to a GH repository - then i would suggest to use https://github.com/react-tooltip/react-tooltip so that does not change anymore no matter who the maintainer will be.

**Comment by elionntechguy** [comment]
hey @pdeszynski i'm trying to install your library but it's not working.
i'm installing it correctly but in node_modules/react-tooltip-rc/dist there's a tar.gz file instead of index.js

**Comment by pdeszynski** [comment]
@elionntechguy sorry for that 😞  I was playing with github actions to setup builds and I didn't think anyone really uses it. Released fixed version with files inside

<img width="344" alt="Zrzut ekranu 2022-10-3 o 08 00 35" src="https://user-images.githubusercontent.com/1628168/193510392-8923a41c-2cff-4cdb-89fc-22aa8e0ff32c.png">

**Comment by elionntechguy** [comment]
@pdeszynski thanks, but i'm still having the problem of the tooltip not closing when you go off it with clickable=true property. Would you be able to help me?

**Comment by elionntechguy** [comment]
> @elionntechguy sorry for that 😞 I was playing with github actions to setup builds and I didn't think anyone really uses it yet. Released fixed version with files inside and from now on I promise it will be stable
> 
> <img alt="Zrzut ekranu 2022-10-3 o 08 00 35" width="344" src="https://user-images.githubusercontent.com/1628168/193510392-8923a41c-2cff-4cdb-89fc-22aa8e0ff32c.png">

> @pdeszynski thanks, but i'm still having the problem of the tooltip not closing when you go off it with clickable=true property. Would you be able to help me?

pinging again @pdeszynski

**Comment by chiratnachakraborty-betterhalf** [comment]
Is the issue fixed now...part of npm-package 4.2.21?

**Comment by pdeszynski** [comment]
> @pdeszynski thanks, but i'm still having the problem of the tooltip not closing when you go off it with clickable=true property. Would you be able to help me?

Please open an issue, though I was not able to reproduce that problem https://pdeszynski.github.io/react-tooltip/?path=/story/example-advanced-features--all-props&args=effect:solid;clickable:true

**Comment by DarioLopes** [comment]
Yep, still having the issue, setting "strict mode" to false on Next.js seems to do the trick, but is a bit awkward!

Hope it gets fixed soon, anyway, thanks for the work!

**Comment by stuarthallows** [comment]
I created a [tooltip component ](https://github.com/stuarthallows/react-tooltip) using [Floating UI](https://floating-ui.com/) (that works fine with React 18). It turns out that once you know how to use Floating UI it's pretty simple to create your own highly customizable tooltip, and you don't actually need react-tooltip any more.
![image](https://user-images.githubusercontent.com/1193012/194782522-f9a9fbb9-1718-4564-8a5e-772a6ee086cc.png)

**Comment by danielbarion** [comment]
Hi guys, we've released a new version that supports React 18 (with the strict mode), I'll close that issue, please try the latest version.

If needs anything else, please let us know, thanks!

**Comment by skident** [comment]
Hey guys, I just migrated to React 18 and seems like experiencing almost the same issue described here. The minor difference is that my tooltip is not hiding only when I apply a custom style on it. Otherwise it works fine, any ideas on that?

**Comment by gabrieljablonski** [comment]
@skident are you using v4 or v5? If on V4, please see if it's possible to upgrade to V5, since we're not maintaining V4 any longer.

If on V5, please check [this section on the troubleshooting page](https://react-tooltip.com/docs/troubleshooting#the-tooltip-doesnt-close), or open a new issue with more details.

**Comment by skident** [comment]
@gabrieljablonski, yes I am using V5 and thanks for the troubleshooting page, the problem was with the `opacity` property.
